/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Assignment_1;

import Assignment_2.LoginFrom;
import java.awt.Color;

/**
 *
 * @author ToanNM_PC09504
 */
public class QuanLyKhoGiay extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public QuanLyKhoGiay() {
        initComponents();
        pnlMenu.setBackground(new java.awt.Color(0,0,0,1));
        setTitle("Quản Lý Kho Giày");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrAZ = new javax.swing.ButtonGroup();
        bgrCaoThap = new javax.swing.ButtonGroup();
        pnlMenu = new javax.swing.JPanel();
        lblQuanLyKhoGiay = new javax.swing.JLabel();
        lblQuanLyNhanVien = new javax.swing.JLabel();
        lblBanHang = new javax.swing.JLabel();
        lblThongKe = new javax.swing.JLabel();
        lblTroGiup = new javax.swing.JLabel();
        lblTaiKhoan = new javax.swing.JLabel();
        lblDangXuat = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnSapXepTheoTen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSapXepTheoGia = new javax.swing.JButton();
        rdoAZ = new javax.swing.JRadioButton();
        rdoZA = new javax.swing.JRadioButton();
        rdoCaoThap = new javax.swing.JRadioButton();
        rdoThapCao = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtMaGiay2 = new javax.swing.JTextField();
        txtTenGiay2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cboMauSac2 = new javax.swing.JComboBox<>();
        cboKichThuoc2 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        spnSoLuong2 = new javax.swing.JSpinner();
        txtDonGia2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setPreferredSize(new java.awt.Dimension(230, 540));
        pnlMenu.setLayout(new java.awt.GridLayout(0, 1));

        lblQuanLyKhoGiay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblQuanLyKhoGiay.setForeground(new java.awt.Color(0, 0, 255));
        lblQuanLyKhoGiay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuanLyKhoGiay.setText("QUẢN LÝ KHO GIÀY");
        lblQuanLyKhoGiay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblQuanLyKhoGiay.setPreferredSize(new java.awt.Dimension(250, 250));
        lblQuanLyKhoGiay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuanLyKhoGiayMouseClicked(evt);
            }
        });
        pnlMenu.add(lblQuanLyKhoGiay);

        lblQuanLyNhanVien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblQuanLyNhanVien.setForeground(new java.awt.Color(0, 0, 255));
        lblQuanLyNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuanLyNhanVien.setText("QUẢN LÝ NHÂN VIÊN");
        lblQuanLyNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblQuanLyNhanVien.setPreferredSize(new java.awt.Dimension(250, 250));
        lblQuanLyNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuanLyNhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuanLyNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuanLyNhanVienMouseExited(evt);
            }
        });
        pnlMenu.add(lblQuanLyNhanVien);

        lblBanHang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBanHang.setForeground(new java.awt.Color(0, 0, 255));
        lblBanHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanHang.setText("LỊCH SỬ");
        pnlMenu.add(lblBanHang);

        lblThongKe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblThongKe.setForeground(new java.awt.Color(0, 0, 255));
        lblThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThongKe.setText("THỐNG KÊ");
        lblThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblThongKe.setPreferredSize(new java.awt.Dimension(250, 250));
        lblThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThongKeMouseClicked(evt);
            }
        });
        pnlMenu.add(lblThongKe);

        lblTroGiup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTroGiup.setForeground(new java.awt.Color(0, 0, 255));
        lblTroGiup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTroGiup.setText("TRỢ GIÚP");
        lblTroGiup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTroGiup.setPreferredSize(new java.awt.Dimension(250, 250));
        pnlMenu.add(lblTroGiup);

        lblTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTaiKhoan.setForeground(new java.awt.Color(0, 0, 255));
        lblTaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTaiKhoan.setText("TÀI KHOẢN");
        lblTaiKhoan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTaiKhoan.setPreferredSize(new java.awt.Dimension(250, 250));
        lblTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTaiKhoanMouseClicked(evt);
            }
        });
        pnlMenu.add(lblTaiKhoan);

        lblDangXuat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDangXuat.setForeground(new java.awt.Color(0, 0, 255));
        lblDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDangXuat.setText("ĐĂNG XUẤT");
        lblDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblDangXuat.setPreferredSize(new java.awt.Dimension(250, 250));
        lblDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseClicked(evt);
            }
        });
        pnlMenu.add(lblDangXuat);

        getContentPane().add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 540));

        jPanel2.setPreferredSize(new java.awt.Dimension(710, 540));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("QUẢN LÝ GIÀY THỂ THAO");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image2/GiayHong.jpg"))); // NOI18N

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/132289_search_search.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");

        jPanel1.setLayout(new java.awt.GridLayout(0, 1, 0, 25));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/132335_add_add.png"))); // NOI18N
        btnThem.setText("Thêm");
        jPanel1.add(btnThem);

        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/132347_accept_accept.png"))); // NOI18N
        btnCapNhat.setText("Cập Nhật");
        jPanel1.add(btnCapNhat);

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/132192_delete_delete.png"))); // NOI18N
        btnXoa.setText("Xoá");
        jPanel1.add(btnXoa);

        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/132188_text_text.png"))); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        jPanel1.add(btnLamMoi);

        btnSapXepTheoTen.setText("Sắp Xếp Theo Tên");
        btnSapXepTheoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepTheoTenActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Giày", "Tên Giày", "Màu Sắc", "Kích Thước", "Số Lượng", "Đơn Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnSapXepTheoGia.setText("Sắp Xếp Theo Giá");
        btnSapXepTheoGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepTheoGiaActionPerformed(evt);
            }
        });

        bgrAZ.add(rdoAZ);
        rdoAZ.setText("A-Z");
        rdoAZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoAZActionPerformed(evt);
            }
        });

        bgrAZ.add(rdoZA);
        rdoZA.setText("Z-A");

        bgrCaoThap.add(rdoCaoThap);
        rdoCaoThap.setText("Cao-Thấp");

        bgrCaoThap.add(rdoThapCao);
        rdoThapCao.setText("Thấp-Cao");

        jLabel16.setText("Mã Giày :");

        jLabel17.setText("Tên Giày :");

        jLabel18.setText("Màu Sắc :");

        cboMauSac2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đen", "Trắng", "Xanh Dương", "Hồng", "Tím", "Xám", " " }));

        cboKichThuoc2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45" }));

        jLabel19.setText("Kích Thước :");

        jLabel20.setText("Số Lượng :");

        txtDonGia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonGia2ActionPerformed(evt);
            }
        });

        jLabel21.setText("Đơn Giá :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19))
                    .addComponent(jLabel21)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDonGia2)
                    .addComponent(cboKichThuoc2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboMauSac2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTenGiay2)
                    .addComponent(txtMaGiay2)
                    .addComponent(spnSoLuong2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtMaGiay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtTenGiay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cboMauSac2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cboKichThuoc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(spnSoLuong2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtDonGia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(btnTimKiem))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSapXepTheoGia, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSapXepTheoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rdoCaoThap)
                                .addGap(37, 37, 37)
                                .addComponent(rdoThapCao))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rdoAZ)
                                .addGap(73, 73, 73)
                                .addComponent(rdoZA)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTimKiem))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSapXepTheoTen)
                    .addComponent(rdoAZ)
                    .addComponent(rdoZA))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSapXepTheoGia)
                    .addComponent(rdoCaoThap)
                    .addComponent(rdoThapCao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 730, 540));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Gi.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdoAZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoAZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoAZActionPerformed

    private void btnSapXepTheoGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepTheoGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSapXepTheoGiaActionPerformed

    private void btnSapXepTheoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepTheoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSapXepTheoTenActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void txtDonGia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonGia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonGia2ActionPerformed

    private void lblQuanLyKhoGiayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyKhoGiayMouseClicked
        
    }//GEN-LAST:event_lblQuanLyKhoGiayMouseClicked

    private void lblQuanLyNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyNhanVienMouseClicked
        QuanLyNhanVien qlnv = new QuanLyNhanVien();
        qlnv.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblQuanLyNhanVienMouseClicked

    private void lblQuanLyNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyNhanVienMouseEntered

    }//GEN-LAST:event_lblQuanLyNhanVienMouseEntered

    private void lblQuanLyNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyNhanVienMouseExited

    }//GEN-LAST:event_lblQuanLyNhanVienMouseExited

    private void lblThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeMouseClicked
        ThongKe tk = new ThongKe();
        tk.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblThongKeMouseClicked

    private void lblDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseClicked
        LoginFrom login = new LoginFrom();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblDangXuatMouseClicked

    private void lblTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTaiKhoanMouseClicked
        QuanLyTaiKhoan qltk = new QuanLyTaiKhoan();
        qltk.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblTaiKhoanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhoGiay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhoGiay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhoGiay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhoGiay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyKhoGiay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrAZ;
    private javax.swing.ButtonGroup bgrCaoThap;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSapXepTheoGia;
    private javax.swing.JButton btnSapXepTheoTen;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboKichThuoc2;
    private javax.swing.JComboBox<String> cboMauSac2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBanHang;
    private javax.swing.JLabel lblDangXuat;
    private javax.swing.JLabel lblQuanLyKhoGiay;
    private javax.swing.JLabel lblQuanLyNhanVien;
    private javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JLabel lblThongKe;
    private javax.swing.JLabel lblTroGiup;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JRadioButton rdoAZ;
    private javax.swing.JRadioButton rdoCaoThap;
    private javax.swing.JRadioButton rdoThapCao;
    private javax.swing.JRadioButton rdoZA;
    private javax.swing.JSpinner spnSoLuong2;
    private javax.swing.JTextField txtDonGia2;
    private javax.swing.JTextField txtMaGiay2;
    private javax.swing.JTextField txtTenGiay2;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
