/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Assignment_1;

import Assignment_2.LoginFrom;

/**
 *
 * @author ToanNM_PC09504
 */
public class ThongKe extends javax.swing.JFrame {

    /**
     * Creates new form KhongKe
     */
    public ThongKe() {
        initComponents();
        setLocationRelativeTo(null);
        pnlMenu.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        lblQuanLyKhoGiay = new javax.swing.JLabel();
        lblQuanLyNhanVien = new javax.swing.JLabel();
        lblBanHang = new javax.swing.JLabel();
        lblThongKe = new javax.swing.JLabel();
        lblTroGiup = new javax.swing.JLabel();
        lblTaiKhoan = new javax.swing.JLabel();
        lblDangXuat = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tbpThongKe = new javax.swing.JTabbedPane();
        tbpThongKe_pnlDoanhThu = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblThongKeTheoThang = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        rdoBang = new javax.swing.JRadioButton();
        rdoBieuDo = new javax.swing.JRadioButton();
        tbpThongKe_pnlThongKeChiTiet = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongKeChiTiet = new javax.swing.JTable();
        pnlThanhDoanhThu = new javax.swing.JPanel();
        pnlTongDonHang = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        pnlDoanhThuNgay = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pnlDoanhThuThang = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        pnlDoanhThuNam = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        pnlChonThoiGian = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thống Kê");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setLayout(new java.awt.GridLayout(0, 1));

        lblQuanLyKhoGiay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblQuanLyKhoGiay.setForeground(new java.awt.Color(0, 0, 255));
        lblQuanLyKhoGiay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuanLyKhoGiay.setText("QUẢN LÝ KHO GIÀY");
        lblQuanLyKhoGiay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblQuanLyKhoGiay.setPreferredSize(new java.awt.Dimension(250, 250));
        lblQuanLyKhoGiay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuanLyKhoGiayMouseClicked(evt);
            }
        });
        pnlMenu.add(lblQuanLyKhoGiay);

        lblQuanLyNhanVien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblQuanLyNhanVien.setForeground(new java.awt.Color(0, 0, 255));
        lblQuanLyNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuanLyNhanVien.setText("QUẢN LÝ NHÂN VIÊN");
        lblQuanLyNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblQuanLyNhanVien.setPreferredSize(new java.awt.Dimension(250, 250));
        lblQuanLyNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuanLyNhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuanLyNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuanLyNhanVienMouseExited(evt);
            }
        });
        pnlMenu.add(lblQuanLyNhanVien);

        lblBanHang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBanHang.setForeground(new java.awt.Color(0, 0, 255));
        lblBanHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanHang.setText("LỊCH SỬ");
        pnlMenu.add(lblBanHang);

        lblThongKe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblThongKe.setForeground(new java.awt.Color(0, 0, 255));
        lblThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThongKe.setText("THỐNG KÊ");
        lblThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblThongKe.setPreferredSize(new java.awt.Dimension(250, 250));
        lblThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThongKeMouseClicked(evt);
            }
        });
        pnlMenu.add(lblThongKe);

        lblTroGiup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTroGiup.setForeground(new java.awt.Color(0, 0, 255));
        lblTroGiup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTroGiup.setText("TRỢ GIÚP");
        lblTroGiup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTroGiup.setPreferredSize(new java.awt.Dimension(250, 250));
        pnlMenu.add(lblTroGiup);

        lblTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTaiKhoan.setForeground(new java.awt.Color(0, 0, 255));
        lblTaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTaiKhoan.setText("TÀI KHOẢN");
        lblTaiKhoan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTaiKhoan.setPreferredSize(new java.awt.Dimension(250, 250));
        lblTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTaiKhoanMouseClicked(evt);
            }
        });
        pnlMenu.add(lblTaiKhoan);

        lblDangXuat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDangXuat.setForeground(new java.awt.Color(0, 0, 255));
        lblDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDangXuat.setText("ĐĂNG XUẤT");
        lblDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblDangXuat.setPreferredSize(new java.awt.Dimension(250, 250));
        lblDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseClicked(evt);
            }
        });
        pnlMenu.add(lblDangXuat);

        getContentPane().add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 540));

        tblThongKeTheoThang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tháng", "Tổng Sản Phẩm Bán", "Tổng Tiền Bán", "Tổng Giảm Giá", "Doanh Thu"
            }
        ));
        jScrollPane2.setViewportView(tblThongKeTheoThang);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 37, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        jLabel2.setText("Năm :");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024", "2025" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        rdoBang.setText("Bảng");

        rdoBieuDo.setText("Biểu Đồ");
        rdoBieuDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoBieuDoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tbpThongKe_pnlDoanhThuLayout = new javax.swing.GroupLayout(tbpThongKe_pnlDoanhThu);
        tbpThongKe_pnlDoanhThu.setLayout(tbpThongKe_pnlDoanhThuLayout);
        tbpThongKe_pnlDoanhThuLayout.setHorizontalGroup(
            tbpThongKe_pnlDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbpThongKe_pnlDoanhThuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tbpThongKe_pnlDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tbpThongKe_pnlDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(rdoBang)
                    .addComponent(rdoBieuDo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        tbpThongKe_pnlDoanhThuLayout.setVerticalGroup(
            tbpThongKe_pnlDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbpThongKe_pnlDoanhThuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rdoBang)
                .addGap(18, 18, 18)
                .addComponent(rdoBieuDo)
                .addGap(0, 125, Short.MAX_VALUE))
            .addGroup(tbpThongKe_pnlDoanhThuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbpThongKe.addTab("Doanh thu", tbpThongKe_pnlDoanhThu);

        tblThongKeChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Sản Phẩm", "Tên Sản Phẩm", "Màu Sắc", "Kích Thước", "Số Lượng"
            }
        ));
        jScrollPane1.setViewportView(tblThongKeChiTiet);

        javax.swing.GroupLayout tbpThongKe_pnlThongKeChiTietLayout = new javax.swing.GroupLayout(tbpThongKe_pnlThongKeChiTiet);
        tbpThongKe_pnlThongKeChiTiet.setLayout(tbpThongKe_pnlThongKeChiTietLayout);
        tbpThongKe_pnlThongKeChiTietLayout.setHorizontalGroup(
            tbpThongKe_pnlThongKeChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbpThongKe_pnlThongKeChiTietLayout.createSequentialGroup()
                .addGap(0, 80, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        tbpThongKe_pnlThongKeChiTietLayout.setVerticalGroup(
            tbpThongKe_pnlThongKeChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbpThongKe_pnlThongKeChiTietLayout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbpThongKe.addTab("Thống Kê Chi Tiết", tbpThongKe_pnlThongKeChiTiet);

        pnlThanhDoanhThu.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        pnlTongDonHang.setBackground(new java.awt.Color(0, 0, 255));
        pnlTongDonHang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" Tổng Đơn Hàng");
        pnlTongDonHang.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 7, 136, -1));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 0, 255));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText(" 100");
        jTextField1.setBorder(null);
        jTextField1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        pnlTongDonHang.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 103, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" Thành Công:");
        pnlTongDonHang.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 62, -1, 23));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" Bị Huỷ:");
        pnlTongDonHang.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 98, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(0, 0, 255));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setText("95");
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        pnlTongDonHang.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 62, 76, 23));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(0, 0, 255));
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField3.setText("5");
        jTextField3.setBorder(null);
        pnlTongDonHang.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 98, 76, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Đơn Hàng");
        pnlTongDonHang.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 32, -1, -1));

        pnlThanhDoanhThu.add(pnlTongDonHang);

        pnlDoanhThuNgay.setBackground(new java.awt.Color(255, 0, 0));
        pnlDoanhThuNgay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" Doanh Thu Ngày");
        pnlDoanhThuNgay.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 7, -1, -1));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(255, 0, 0));
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField4.setText(" 100");
        jTextField4.setBorder(null);
        jTextField4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        pnlDoanhThuNgay.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 129, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" Thành Công:");
        pnlDoanhThuNgay.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, 24));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 0, 0));
        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField5.setText("95");
        jTextField5.setBorder(null);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        pnlDoanhThuNgay.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 80, 24));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(255, 0, 0));
        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField6.setText("5");
        jTextField6.setBorder(null);
        pnlDoanhThuNgay.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 98, 79, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(" Bị Huỷ:");
        pnlDoanhThuNgay.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 98, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("VNĐ");
        pnlDoanhThuNgay.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 30, -1, -1));

        pnlThanhDoanhThu.add(pnlDoanhThuNgay);

        pnlDoanhThuThang.setBackground(new java.awt.Color(0, 153, 0));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(" Doanh Thu Tháng");

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(51, 153, 0));
        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField7.setText(" 100");
        jTextField7.setBorder(null);
        jTextField7.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(" Thành Công:");

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(0, 153, 0));
        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField8.setText("95");
        jTextField8.setBorder(null);

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(0, 153, 0));
        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 255, 255));
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField9.setText("5");
        jTextField9.setBorder(null);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(" Bị Huỷ:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("VNĐ");

        javax.swing.GroupLayout pnlDoanhThuThangLayout = new javax.swing.GroupLayout(pnlDoanhThuThang);
        pnlDoanhThuThang.setLayout(pnlDoanhThuThangLayout);
        pnlDoanhThuThangLayout.setHorizontalGroup(
            pnlDoanhThuThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoanhThuThangLayout.createSequentialGroup()
                .addGroup(pnlDoanhThuThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDoanhThuThangLayout.createSequentialGroup()
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel20))
                    .addGroup(pnlDoanhThuThangLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(6, 6, 6)
                        .addComponent(jTextField8))
                    .addGroup(pnlDoanhThuThangLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(41, 41, 41)
                        .addComponent(jTextField9)))
                .addGap(4, 4, 4))
        );
        pnlDoanhThuThangLayout.setVerticalGroup(
            pnlDoanhThuThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoanhThuThangLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel12)
                .addGap(8, 8, 8)
                .addGroup(pnlDoanhThuThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(13, 13, 13)
                .addGroup(pnlDoanhThuThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pnlDoanhThuThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)))
        );

        pnlThanhDoanhThu.add(pnlDoanhThuThang);

        pnlDoanhThuNam.setBackground(new java.awt.Color(255, 153, 0));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText(" Doanh Thu Năm");

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(255, 153, 0));
        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(255, 255, 255));
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField10.setText(" 100");
        jTextField10.setBorder(null);
        jTextField10.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(" Thành Công:");

        jTextField11.setEditable(false);
        jTextField11.setBackground(new java.awt.Color(255, 153, 0));
        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(255, 255, 255));
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField11.setText("95");
        jTextField11.setBorder(null);

        jTextField12.setEditable(false);
        jTextField12.setBackground(new java.awt.Color(255, 153, 0));
        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(255, 255, 255));
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField12.setText("5");
        jTextField12.setBorder(null);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(" Bị Huỷ:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("VNĐ");

        javax.swing.GroupLayout pnlDoanhThuNamLayout = new javax.swing.GroupLayout(pnlDoanhThuNam);
        pnlDoanhThuNam.setLayout(pnlDoanhThuNamLayout);
        pnlDoanhThuNamLayout.setHorizontalGroup(
            pnlDoanhThuNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoanhThuNamLayout.createSequentialGroup()
                .addGroup(pnlDoanhThuNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(pnlDoanhThuNamLayout.createSequentialGroup()
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21))
                    .addGroup(pnlDoanhThuNamLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(6, 6, 6)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDoanhThuNamLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(40, 40, 40)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5))
        );
        pnlDoanhThuNamLayout.setVerticalGroup(
            pnlDoanhThuNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoanhThuNamLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel15)
                .addGap(7, 7, 7)
                .addGroup(pnlDoanhThuNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDoanhThuNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(pnlDoanhThuNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDoanhThuNamLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pnlThanhDoanhThu.add(pnlDoanhThuNam);

        jLabel3.setText("Thời Gian:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hôm nay", "Theo Ngày" }));

        jLabel4.setText("Ngày Bắt Đầu");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "24/07/2024" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Ngày Kết Thúc");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "26/07/2024" }));

        jButton1.setText("Tìm Kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlChonThoiGianLayout = new javax.swing.GroupLayout(pnlChonThoiGian);
        pnlChonThoiGian.setLayout(pnlChonThoiGianLayout);
        pnlChonThoiGianLayout.setHorizontalGroup(
            pnlChonThoiGianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChonThoiGianLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1))
        );
        pnlChonThoiGianLayout.setVerticalGroup(
            pnlChonThoiGianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChonThoiGianLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlChonThoiGianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pnlChonThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addComponent(pnlThanhDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(tbpThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlThanhDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(pnlChonThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tbpThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 730, 540));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Gi.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblQuanLyKhoGiayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyKhoGiayMouseClicked
        QuanLyKhoGiay qlkg = new QuanLyKhoGiay();
        qlkg.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblQuanLyKhoGiayMouseClicked

    private void lblQuanLyNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyNhanVienMouseClicked
        QuanLyNhanVien qlnv = new QuanLyNhanVien();
        qlnv.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblQuanLyNhanVienMouseClicked

    private void lblQuanLyNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyNhanVienMouseEntered
        //        lblQuanLyNhanVien.setText("<html><u>Quản Lý Nhân Viên</u></html>");
        //        lblQuanLyNhanVien.setForeground(Color.yellow);
    }//GEN-LAST:event_lblQuanLyNhanVienMouseEntered

    private void lblQuanLyNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyNhanVienMouseExited
        //        lblQuanLyNhanVien.setText("Quên Mật Khẩu");
        //        lblQuanLyNhanVien.setForeground(Color.BLUE);
    }//GEN-LAST:event_lblQuanLyNhanVienMouseExited

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void rdoBieuDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoBieuDoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoBieuDoActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeMouseClicked
        
    }//GEN-LAST:event_lblThongKeMouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void lblDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseClicked
        LoginFrom login = new LoginFrom();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblDangXuatMouseClicked

    private void lblTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTaiKhoanMouseClicked
        QuanLyTaiKhoan qltk = new QuanLyTaiKhoan();
        qltk.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblTaiKhoanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lblBanHang;
    private javax.swing.JLabel lblDangXuat;
    private javax.swing.JLabel lblQuanLyKhoGiay;
    private javax.swing.JLabel lblQuanLyNhanVien;
    private javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JLabel lblThongKe;
    private javax.swing.JLabel lblTroGiup;
    private javax.swing.JPanel pnlChonThoiGian;
    private javax.swing.JPanel pnlDoanhThuNam;
    private javax.swing.JPanel pnlDoanhThuNgay;
    private javax.swing.JPanel pnlDoanhThuThang;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlThanhDoanhThu;
    private javax.swing.JPanel pnlTongDonHang;
    private javax.swing.JRadioButton rdoBang;
    private javax.swing.JRadioButton rdoBieuDo;
    private javax.swing.JTable tblThongKeChiTiet;
    private javax.swing.JTable tblThongKeTheoThang;
    private javax.swing.JTabbedPane tbpThongKe;
    private javax.swing.JPanel tbpThongKe_pnlDoanhThu;
    private javax.swing.JPanel tbpThongKe_pnlThongKeChiTiet;
    // End of variables declaration//GEN-END:variables
}
