/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Assignment_2;

import java.awt.Color;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ToanNM_PC09504
 */
public class LoginFrom extends javax.swing.JFrame {

    ImageIcon icon;
    Connection ketNoi;
    String ten;

    /**
     * Creates new form LoginFrom
     */
    public LoginFrom() {
        initComponents();
        doiIcon();
        setTitle("Phần Mềm Quản Lý Giày");
        txtUserName.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtPassWord.setBackground(new java.awt.Color(0, 0, 0, 1));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTen = new javax.swing.JLabel();
        lblTenDangNhap = new javax.swing.JLabel();
        lblMatKhau = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPassWord = new javax.swing.JPasswordField();
        btnDangNhap = new javax.swing.JButton();
        btnDangKy = new javax.swing.JButton();
        lblQuenMatKhau = new javax.swing.JLabel();
        lblNen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ĐĂNG NHẬP");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTen.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTen.setForeground(new java.awt.Color(255, 0, 0));
        lblTen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTen.setText("ĐĂNG NHẬP");
        getContentPane().add(lblTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        lblTenDangNhap.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTenDangNhap.setText("Tên Đăng Nhập :");
        getContentPane().add(lblTenDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        lblMatKhau.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblMatKhau.setText("Mật Khẩu :");
        getContentPane().add(lblMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        txtUserName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 240, -1));

        txtPassWord.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(txtPassWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 240, -1));

        btnDangNhap.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnDangNhap.setText("Đăng Nhập");
        btnDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDangNhapMouseClicked(evt);
            }
        });
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 120, -1));

        btnDangKy.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnDangKy.setText("Thoát");
        btnDangKy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDangKyMouseClicked(evt);
            }
        });
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 100, -1));

        lblQuenMatKhau.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblQuenMatKhau.setText("Quên Mật Khẩu");
        lblQuenMatKhau.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblQuenMatKhau.setMaximumSize(new java.awt.Dimension(90, 16));
        lblQuenMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuenMatKhauMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuenMatKhauMouseExited(evt);
            }
        });
        getContentPane().add(lblQuenMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 120, 20));

        lblNen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/GiayTT.jpg"))); // NOI18N
        getContentPane().add(lblNen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void doiIcon() {
        icon = new ImageIcon("src/Image/icon_shoe.png");
        setIconImage(icon.getImage());
    }

    public boolean check() {
        String userName = txtUserName.getText();
        String passWord = txtPassWord.getText();

        if (txtUserName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa nhập tên đăng nhập");
            //txtUserName.setBackground(Color.yellow);
            txtUserName.setBackground(new java.awt.Color(255, 0, 0, 128));
            txtUserName.requestFocus();
            txtPassWord.setText("");
            return false;
        } else if (txtPassWord.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa nhập mật khẩu");
            txtPassWord.setBackground(new java.awt.Color(255, 0, 0, 128));
            txtUserName.setBackground(new java.awt.Color(0, 0, 0, 1));
            txtPassWord.requestFocus();
            return false;

        }
        return true;
    }
    private void lblQuenMatKhauMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenMatKhauMouseEntered
        lblQuenMatKhau.setText("<html><u>Quên Mật Khẩu</u></html>");
        lblQuenMatKhau.setForeground(Color.yellow);
    }//GEN-LAST:event_lblQuenMatKhauMouseEntered

    private void lblQuenMatKhauMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenMatKhauMouseExited
        lblQuenMatKhau.setText("Quên Mật Khẩu");
        lblQuenMatKhau.setForeground(Color.black);
    }//GEN-LAST:event_lblQuenMatKhauMouseExited

    private void btnDangKyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangKyMouseClicked

    }//GEN-LAST:event_btnDangKyMouseClicked
    public void KetNoiCSDL() throws ClassNotFoundException, SQLException {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String url = "jdbc:sqlserver://localhost:1433; databaseName = CuaHangGiay";
        String user = "sa";
        String pass = "123456";
        ketNoi = DriverManager.getConnection(url, user, pass);
    }
    private void btnDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangNhapMouseClicked
        if (check()) {
            String userName = txtUserName.getText();
            String passWord = txtPassWord.getText();
            try {
                KetNoiCSDL();
                String sql = "SELECT Quyen,HoTen FROM NguoiDung WHERE TenDangNhap = ? AND MatKhau = ?";
                PreparedStatement cauLenh = ketNoi.prepareStatement(sql);
                cauLenh.setString(1, txtUserName.getText());
                cauLenh.setString(2, txtPassWord.getText());
                ResultSet ketQua = cauLenh.executeQuery();

                if (ketQua.next() == true) {
                    String quyen = ketQua.getString(1);
                    String hoTen = ketQua.getString(2);
                    FileWriter fw = null;
                    try {
                        fw = new FileWriter("src\\Ten\\TenNV.txt", false);
                        fw.write(hoTen);
                        fw.write("\n");
                        System.out.println("Lưu thành công");
                    } catch (Exception e) {
                        System.out.println("Lưu thất bại");
                    } finally {
                        try {
                            fw.close();
                        } catch (IOException e) {
                            System.out.println("Lỗi đóng file");
                        }
                    }
                    if (quyen.equals("Admin")) {
                        PhanMem qlkg = new PhanMem();
                        qlkg.setVisible(true);
                        dispose();
                    } else {
                        QuanLyHoaDon qlhd = new QuanLyHoaDon();
                        qlhd.setVisible(true);
                        dispose();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Sai tên đăng nhập hoặc mật khẩu!");
                    txtUserName.setText("");
                    txtPassWord.setText("");
                    txtUserName.setBackground(new java.awt.Color(255, 0, 0, 128));
                    txtPassWord.setBackground(new java.awt.Color(0, 0, 0, 1));
                    txtUserName.requestFocus();
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(LoginFrom.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(LoginFrom.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnDangNhapMouseClicked

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
       
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnDangKyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKy;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblNen;
    private javax.swing.JLabel lblQuenMatKhau;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblTenDangNhap;
    private javax.swing.JPasswordField txtPassWord;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
