/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Assignment_2;

import java.awt.Color;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ToanNM_PC09504
 */
public class QuanLyHoaDon extends javax.swing.JFrame {

    ImageIcon icon;
    Connection ketNoi;
    DefaultComboBoxModel model_boxMSp = new DefaultComboBoxModel();
    DefaultComboBoxModel model_boxTSp = new DefaultComboBoxModel();
    DefaultComboBoxModel model_boxMau = new DefaultComboBoxModel();
    DefaultComboBoxModel model_boxKichThuoc = new DefaultComboBoxModel();
    DefaultTableModel modelGioHang = new DefaultTableModel();
    LocalDate today = LocalDate.now();
    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    String fmd = today.format(dtf);

    /**
     * Creates new form QuanLyHoaDon
     */
    public QuanLyHoaDon() throws ClassNotFoundException, SQLException {
        initComponents();
        setTitle("Phần Mềm Quản Lý Giày");
        doiIcon();
        DoDuLieuLenComboBox();
        DatTenCotSanPham();
        DoDuLieuLenBangGioHang();
        TongTien();
        txtNgayTao.setText(fmd);
        txtTongTien_pnlHoaDon.setText(txtTongTien.getText());
        maHoaDon();
        txtTenNhanVien.setText(docFile());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlTaoHoaDon = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtTenKhachHang = new javax.swing.JTextField();
        txtSoDienThoaiKhachHang = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboPTThanhToan = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        txtTienKhachDua = new javax.swing.JTextField();
        txtTienThua = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnThanhToan = new javax.swing.JButton();
        btnTaoHoaDon = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        pnlGioHang = new javax.swing.JPanel();
        btnXoa = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblChiTietHoaDon = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        tbrMenu_btnNew = new javax.swing.JButton();
        tbrMenu_btnPrint = new javax.swing.JButton();
        tbrMenu_btnExit = new javax.swing.JButton();
        pnlHoaDon = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaHoaDon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenNhanVien = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTenKhachHang_pnlHoaDon = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNgayTao = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtTongTien_pnlHoaDon = new javax.swing.JTextField();
        pnlSanPham = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cboMaSanPham = new javax.swing.JComboBox<>();
        txtTimKiem_MaSanPham = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cboTenSanPham = new javax.swing.JComboBox<>();
        txtTimKiem_TenSanPham = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cboMauSac = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cboKichThuoc = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        lblSoLuongKho = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnThem_GioHang = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnuFile = new javax.swing.JMenu();
        mnuFile_New = new javax.swing.JMenuItem();
        mnuFile_Open = new javax.swing.JMenuItem();
        mnuFile_Save = new javax.swing.JMenuItem();
        mnuFile_Print = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuFile_Exit = new javax.swing.JMenuItem();
        mnuEdit = new javax.swing.JMenu();
        mnuEdit_DoiMatKhau = new javax.swing.JMenuItem();
        mnuSystem = new javax.swing.JMenu();
        mnuSystem_About = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlTaoHoaDon.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tạo Hoá Đơn", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel13.setText("Tên Khách Hàng:");

        jLabel14.setText("Số Điện Thoại:");

        txtTenKhachHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenKhachHangKeyReleased(evt);
            }
        });

        jLabel5.setText("Tổng Tiền:");

        jLabel6.setText("Phương Thức Thanh Toán");

        cboPTThanhToan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiền Mặt", "Thẻ Tín Dụng", "Chuyển Khoản" }));

        jLabel7.setText("Tiền Khách Đưa:");

        jLabel8.setText("Tiền Thừa:");

        txtTongTien.setEditable(false);
        txtTongTien.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongTienActionPerformed(evt);
            }
        });

        txtTienKhachDua.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTienKhachDua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienKhachDuaKeyReleased(evt);
            }
        });

        txtTienThua.setEditable(false);
        txtTienThua.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnThanhToan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/132341_dollar_coin.png"))); // NOI18N
        btnThanhToan.setText("Thanh Toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        btnTaoHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/132293_notes_notes.png"))); // NOI18N
        btnTaoHoaDon.setText("Tạo Hoá Đơn");
        btnTaoHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoHoaDonActionPerformed(evt);
            }
        });

        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/132192_delete_delete.png"))); // NOI18N
        btnHuy.setText("Huỷ");

        jLabel1.setText("Giới Tính :");

        buttonGroup1.add(rdoNam);
        rdoNam.setText("Nam");

        buttonGroup1.add(rdoNu);
        rdoNu.setText("Nữ");

        javax.swing.GroupLayout pnlTaoHoaDonLayout = new javax.swing.GroupLayout(pnlTaoHoaDon);
        pnlTaoHoaDon.setLayout(pnlTaoHoaDonLayout);
        pnlTaoHoaDonLayout.setHorizontalGroup(
            pnlTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(pnlTaoHoaDonLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTaoHoaDonLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(12, 12, 12)
                        .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTaoHoaDonLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(24, 24, 24)
                        .addComponent(txtSoDienThoaiKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTaoHoaDonLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(51, 51, 51)
                        .addComponent(rdoNam, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rdoNu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTaoHoaDonLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(5, 5, 5)
                        .addComponent(cboPTThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTaoHoaDonLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(50, 50, 50)
                        .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTaoHoaDonLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTaoHoaDonLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(50, 50, 50)
                        .addComponent(txtTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlTaoHoaDonLayout.createSequentialGroup()
                        .addComponent(btnTaoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        pnlTaoHoaDonLayout.setVerticalGroup(
            pnlTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaoHoaDonLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(pnlTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTaoHoaDonLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel13))
                    .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoDienThoaiKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(19, 19, 19)
                .addGroup(pnlTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdoNam)
                        .addComponent(rdoNu)))
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(pnlTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTaoHoaDonLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cboPTThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTaoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnlGioHang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Giỏ Hàng", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Trash.png"))); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        tblChiTietHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng", "Đơn Giá", "Giảm Giá", "Thành Tiền", "Huỷ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblChiTietHoaDon);
        if (tblChiTietHoaDon.getColumnModel().getColumnCount() > 0) {
            tblChiTietHoaDon.getColumnModel().getColumn(0).setMinWidth(20);
            tblChiTietHoaDon.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblChiTietHoaDon.getColumnModel().getColumn(2).setPreferredWidth(85);
            tblChiTietHoaDon.getColumnModel().getColumn(3).setPreferredWidth(50);
            tblChiTietHoaDon.getColumnModel().getColumn(4).setPreferredWidth(40);
            tblChiTietHoaDon.getColumnModel().getColumn(5).setPreferredWidth(45);
            tblChiTietHoaDon.getColumnModel().getColumn(7).setMinWidth(40);
            tblChiTietHoaDon.getColumnModel().getColumn(7).setPreferredWidth(20);
            tblChiTietHoaDon.getColumnModel().getColumn(7).setMaxWidth(40);
        }

        javax.swing.GroupLayout pnlGioHangLayout = new javax.swing.GroupLayout(pnlGioHang);
        pnlGioHang.setLayout(pnlGioHangLayout);
        pnlGioHangLayout.setHorizontalGroup(
            pnlGioHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGioHangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXoa)
                .addContainerGap())
            .addComponent(jScrollPane2)
        );
        pnlGioHangLayout.setVerticalGroup(
            pnlGioHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGioHangLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXoa))
        );

        jToolBar1.setRollover(true);

        tbrMenu_btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/132335_add_add.png"))); // NOI18N
        tbrMenu_btnNew.setText("New");
        tbrMenu_btnNew.setFocusable(false);
        tbrMenu_btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrMenu_btnNew.setMargin(new java.awt.Insets(2, 25, 2, 25));
        tbrMenu_btnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrMenu_btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrMenu_btnNewActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrMenu_btnNew);

        tbrMenu_btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/132184_printer.png"))); // NOI18N
        tbrMenu_btnPrint.setText("Print");
        tbrMenu_btnPrint.setFocusable(false);
        tbrMenu_btnPrint.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrMenu_btnPrint.setMargin(new java.awt.Insets(2, 25, 2, 25));
        tbrMenu_btnPrint.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(tbrMenu_btnPrint);

        tbrMenu_btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Log out.png"))); // NOI18N
        tbrMenu_btnExit.setText("Exit");
        tbrMenu_btnExit.setFocusable(false);
        tbrMenu_btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrMenu_btnExit.setMargin(new java.awt.Insets(2, 25, 2, 25));
        tbrMenu_btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrMenu_btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrMenu_btnExitActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrMenu_btnExit);

        pnlHoaDon.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hoá Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        pnlHoaDon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Mã Hoá Đơn :");
        pnlHoaDon.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 25, 127, 43));

        txtMaHoaDon.setEditable(false);
        txtMaHoaDon.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMaHoaDon.setText("203");
        pnlHoaDon.add(txtMaHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 25, 140, 43));

        jLabel3.setText("Tên Nhân Viên :");
        pnlHoaDon.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 68, 127, 43));

        txtTenNhanVien.setEditable(false);
        pnlHoaDon.add(txtTenNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 68, 140, 43));

        jLabel4.setText("Tên Khách Hàng :");
        pnlHoaDon.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 111, 127, 43));

        txtTenKhachHang_pnlHoaDon.setEditable(false);
        pnlHoaDon.add(txtTenKhachHang_pnlHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 111, 140, 43));

        jLabel10.setText("Ngày Tạo :");
        pnlHoaDon.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 154, 127, 43));

        txtNgayTao.setEditable(false);
        txtNgayTao.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNgayTao.setText("25/07/2024");
        pnlHoaDon.add(txtNgayTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 154, 140, 43));

        jLabel19.setText("Tổng Tiền :");
        pnlHoaDon.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 197, 127, 43));

        txtTongTien_pnlHoaDon.setEditable(false);
        txtTongTien_pnlHoaDon.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pnlHoaDon.add(txtTongTien_pnlHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 197, 140, 43));

        pnlSanPham.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sản Phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        pnlSanPham.setLayout(new java.awt.GridLayout(7, 3));

        jLabel11.setText("Mã Sản Phẩm :");
        pnlSanPham.add(jLabel11);

        cboMaSanPham.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "001", "002", "003", "004", "005" }));
        cboMaSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMaSanPhamActionPerformed(evt);
            }
        });
        pnlSanPham.add(cboMaSanPham);

        txtTimKiem_MaSanPham.setForeground(new java.awt.Color(204, 204, 204));
        txtTimKiem_MaSanPham.setText("Tìm Kiếm .....");
        txtTimKiem_MaSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTimKiem_MaSanPhamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtTimKiem_MaSanPhamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtTimKiem_MaSanPhamMouseExited(evt);
            }
        });
        txtTimKiem_MaSanPham.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiem_MaSanPhamKeyReleased(evt);
            }
        });
        pnlSanPham.add(txtTimKiem_MaSanPham);

        jLabel12.setText("Tên Sản Phẩm :");
        pnlSanPham.add(jLabel12);

        cboTenSanPham.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nike Air Max", "Adidas Ultraboost", "Puma RS-X", "New Balance 990", "Reebok Classic", "Asics Gel-Kayano", "Saucony Triumph", "Vans Old Skool", "Mizuno Wave Rider", "Brooks Ghost" }));
        cboTenSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTenSanPhamActionPerformed(evt);
            }
        });
        pnlSanPham.add(cboTenSanPham);

        txtTimKiem_TenSanPham.setForeground(new java.awt.Color(204, 204, 204));
        txtTimKiem_TenSanPham.setText("Tìm Kiếm .....");
        txtTimKiem_TenSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTimKiem_TenSanPhamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtTimKiem_TenSanPhamMouseEntered(evt);
            }
        });
        pnlSanPham.add(txtTimKiem_TenSanPham);

        jLabel15.setText("Màu Sắc :");
        pnlSanPham.add(jLabel15);

        pnlSanPham.add(cboMauSac);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Số Lượng");
        pnlSanPham.add(jLabel20);

        jLabel16.setText("Kích Thước :");
        pnlSanPham.add(jLabel16);

        pnlSanPham.add(cboKichThuoc);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Trong Kho: ");
        pnlSanPham.add(jLabel21);

        jLabel17.setText("Số Lượng :");
        pnlSanPham.add(jLabel17);

        txtSoLuong.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtSoLuong.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pnlSanPham.add(txtSoLuong);

        lblSoLuongKho.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSoLuongKho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlSanPham.add(lblSoLuongKho);

        jLabel18.setText("Đơn Giá :");
        pnlSanPham.add(jLabel18);

        txtDonGia.setEditable(false);
        txtDonGia.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtDonGia.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDonGia.setText("0");
        pnlSanPham.add(txtDonGia);
        pnlSanPham.add(jLabel22);

        jButton2.setText("Làm Mới");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pnlSanPham.add(jButton2);

        btnThem_GioHang.setText("Thêm");
        btnThem_GioHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_GioHangActionPerformed(evt);
            }
        });
        pnlSanPham.add(btnThem_GioHang);

        MnuFile.setText("File");
        MnuFile.setMargin(new java.awt.Insets(0, 10, 0, 10));

        mnuFile_New.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mnuFile_New.setText("New");
        MnuFile.add(mnuFile_New);

        mnuFile_Open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mnuFile_Open.setText("Open");
        MnuFile.add(mnuFile_Open);

        mnuFile_Save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnuFile_Save.setText("Save");
        MnuFile.add(mnuFile_Save);

        mnuFile_Print.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuFile_Print.setText("Print");
        MnuFile.add(mnuFile_Print);
        MnuFile.add(jSeparator3);

        mnuFile_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        mnuFile_Exit.setText("Exit");
        MnuFile.add(mnuFile_Exit);

        jMenuBar1.add(MnuFile);

        mnuEdit.setText("Edit");
        mnuEdit.setMargin(new java.awt.Insets(0, 10, 0, 10));

        mnuEdit_DoiMatKhau.setText("Đổi Mật Khẩu");
        mnuEdit_DoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEdit_DoiMatKhauActionPerformed(evt);
            }
        });
        mnuEdit.add(mnuEdit_DoiMatKhau);

        jMenuBar1.add(mnuEdit);

        mnuSystem.setText("System");
        mnuSystem.setMargin(new java.awt.Insets(0, 10, 0, 10));
        mnuSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSystemActionPerformed(evt);
            }
        });

        mnuSystem_About.setText("About");
        mnuSystem_About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSystem_AboutActionPerformed(evt);
            }
        });
        mnuSystem.add(mnuSystem_About);

        jMenuBar1.add(mnuSystem);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlGioHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnlHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTaoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlTaoHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlGioHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void doiIcon() {
        icon = new ImageIcon("src/Image/icon_shoe.png");
        setIconImage(icon.getImage());
    }

    public String docFile() {
        FileReader fr = null;
        StringBuilder sb = new StringBuilder();
        try {
            fr = new FileReader("src\\Ten\\TenNV.txt");
            int kytu;
            while ((kytu = fr.read()) != -1) {
                sb.append((char) kytu);
            }
            return sb.toString();
        } catch (IOException e) {
            System.out.println("Lỗi đọc file: " + e.getMessage());
            return null;
        } finally {
            try {
                if (fr != null) {
                    fr.close();
                }
            } catch (IOException e) {
                System.out.println("Lỗi đóng file: " + e.getMessage());
            }
        }
    }

    public void KetNoiCSDL() throws ClassNotFoundException, SQLException {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String url = "jdbc:sqlserver://localhost:1433; databaseName = CuaHangGiay";
        String user = "sa";
        String pass = "123456";
        ketNoi = DriverManager.getConnection(url, user, pass);
    }

    public void DoDuLieuLenComboBox() throws ClassNotFoundException, SQLException {
        KetNoiCSDL();
        String sql = "SELECT MaSanPham, TenSanPham, MauSac, KichThuoc FROM SanPham";
        PreparedStatement cauLenh = ketNoi.prepareStatement(sql);
        ResultSet ketQua = cauLenh.executeQuery();
        while (ketQua.next() == true) {
            String maSanPham = ketQua.getString(1);
            model_boxMSp.addElement(maSanPham);
            String tenSanPham = ketQua.getString(2);
            model_boxTSp.addElement(tenSanPham);
            String mauSac = ketQua.getString(3);
            model_boxMau.addElement(mauSac);
            String kichThuoc = ketQua.getString(4);
            model_boxKichThuoc.addElement(kichThuoc);
        }
        cboMaSanPham.setModel(model_boxMSp);
        cboTenSanPham.setModel(model_boxTSp);
        cboMauSac.setModel(model_boxMau);
        cboKichThuoc.setModel(model_boxKichThuoc);
        ketNoi.close();
    }

    private void mnuEdit_DoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEdit_DoiMatKhauActionPerformed

    }//GEN-LAST:event_mnuEdit_DoiMatKhauActionPerformed

    private void tbrMenu_btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrMenu_btnExitActionPerformed
        int kq = JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng xuất không", "Thông Báo", JOptionPane.YES_NO_OPTION);
        if (kq == JOptionPane.YES_OPTION) {
            LoginFrom lf = new LoginFrom();
            lf.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_tbrMenu_btnExitActionPerformed

    private void cboMaSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMaSanPhamActionPerformed
        try {
            KetNoiCSDL();
            DecimalFormat df = new DecimalFormat("###,###");
            String sql = "SELECT TenSanPham, MauSac, KichThuoc,SoLuong,DonGia FROM SanPham WHERE maSanPham = ?";
            PreparedStatement cauLenh = ketNoi.prepareStatement(sql);
            cauLenh.setString(1, cboMaSanPham.getSelectedItem().toString());
            ResultSet ketQua = cauLenh.executeQuery();

            while (ketQua.next() == true) {
                cboMauSac.removeAllItems();
                cboKichThuoc.removeAllItems();
                cboTenSanPham.setSelectedItem(ketQua.getString(1));
                String mauSac = ketQua.getString(2);
                model_boxMau.addElement(mauSac);
                cboMauSac.setModel(model_boxMau);
                cboMauSac.setSelectedItem(ketQua.getString(2));

                String kichThuoc = ketQua.getString(3);
                model_boxKichThuoc.addElement(kichThuoc);
                cboKichThuoc.setModel(model_boxKichThuoc);
                cboKichThuoc.setSelectedItem(ketQua.getString(3));
                txtDonGia.setText(df.format(ketQua.getFloat(5)));
                lblSoLuongKho.setText("" + ketQua.getInt(4));

            }
            ketNoi.close();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanLyHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cboMaSanPhamActionPerformed

    private void txtTimKiem_MaSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTimKiem_MaSanPhamMouseClicked
        txtTimKiem_MaSanPham.setText("");
        txtTimKiem_MaSanPham.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtTimKiem_MaSanPhamMouseClicked

    private void txtTimKiem_TenSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTimKiem_TenSanPhamMouseClicked
        txtTimKiem_TenSanPham.setText("");
        txtTimKiem_TenSanPham.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtTimKiem_TenSanPhamMouseClicked

    private void txtTimKiem_MaSanPhamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTimKiem_MaSanPhamMouseExited

    }//GEN-LAST:event_txtTimKiem_MaSanPhamMouseExited

    private void txtTimKiem_MaSanPhamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTimKiem_MaSanPhamMouseEntered
        if (txtTimKiem_MaSanPham.getText().isEmpty()) {
            txtTimKiem_MaSanPham.setText("Tìm Kiếm ....");
            txtTimKiem_MaSanPham.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_txtTimKiem_MaSanPhamMouseEntered

    private void cboTenSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTenSanPhamActionPerformed
        try {
            KetNoiCSDL();
            DecimalFormat df = new DecimalFormat("###,###");
            String sql = "SELECT MaSanPham, MauSac, KichThuoc,SoLuong,DonGia FROM SanPham WHERE TenSanPham = ?";
            PreparedStatement cauLenh = ketNoi.prepareStatement(sql);
            cauLenh.setString(1, cboTenSanPham.getSelectedItem().toString());
            ResultSet ketQua = cauLenh.executeQuery();

            while (ketQua.next() == true) {
                cboMaSanPham.setSelectedItem(ketQua.getString(1));
                cboMauSac.setSelectedItem(ketQua.getString(2));
                cboKichThuoc.setSelectedItem(ketQua.getString(3));
                txtDonGia.setText(df.format(ketQua.getFloat(5)));
                lblSoLuongKho.setText("" + ketQua.getInt(4));
            }
            ketNoi.close();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanLyHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cboTenSanPhamActionPerformed

    private void txtTimKiem_TenSanPhamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTimKiem_TenSanPhamMouseEntered
        if (txtTimKiem_TenSanPham.getText().isEmpty()) {
            txtTimKiem_TenSanPham.setText("Tìm Kiếm ....");
            txtTimKiem_TenSanPham.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_txtTimKiem_TenSanPhamMouseEntered

    private void txtTimKiem_MaSanPhamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiem_MaSanPhamKeyReleased
        try {
            KetNoiCSDL();
            String sql = "SELECT * FROM SanPham WHERE MaSanPham LIKE ?";
            PreparedStatement cauLenh = ketNoi.prepareStatement(sql);
            cauLenh.setString(1, "%" + txtTimKiem_MaSanPham.getText() + "%");
            DecimalFormat df = new DecimalFormat("###,###");
            ResultSet ketQua = cauLenh.executeQuery();
            while (ketQua.next() == true) {
                cboMaSanPham.setSelectedItem(ketQua.getString(1));
                cboMauSac.setSelectedItem(ketQua.getString(2));
                cboKichThuoc.setSelectedItem(ketQua.getString(3));
                txtDonGia.setText(df.format(ketQua.getFloat(5)));
                lblSoLuongKho.setText("" + ketQua.getInt(4));
            }

            ketNoi.close();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PhanMem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PhanMem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtTimKiem_MaSanPhamKeyReleased
    public void DatTenCotSanPham() {
        modelGioHang.addColumn("Mã Sản Phẩm");
        modelGioHang.addColumn("Tên Sản Phẩm");
        modelGioHang.addColumn("Số Lượng");
        modelGioHang.addColumn("Đơn Giá");
        modelGioHang.addColumn("Giảm Giá");
        modelGioHang.addColumn("Thành Tiền");
        // modelGioHang.addColumn("Huỷ");

        tblChiTietHoaDon.setModel(modelGioHang);
    }

    public void DoDuLieuLenBangGioHang() throws ClassNotFoundException, SQLException {
        modelGioHang.setRowCount(0);
        KetNoiCSDL();
        String sql = "SELECT * FROM GioHang";
        PreparedStatement cauLenh = ketNoi.prepareStatement(sql);
        DecimalFormat df = new DecimalFormat("###,###");
        ResultSet ketQua = cauLenh.executeQuery();
        while (ketQua.next() == true) {
            String maSp = ketQua.getString(1);
            String tenSp = ketQua.getString(2);
            int soLuong = ketQua.getInt(3);
            double donGia = ketQua.getDouble(4);
            double giamGia = ketQua.getDouble(5);
            double thanhTien = donGia * soLuong * (1 - (giamGia / 100));

            modelGioHang.addRow(new Object[]{maSp, tenSp, soLuong, df.format(donGia), giamGia, df.format(thanhTien)});
        }
        ketNoi.close();
    }

    public double TongTien() {
        try {
            KetNoiCSDL();
            DecimalFormat df = new DecimalFormat("###,###");
            String sql = "SELECT SUM(DonGia*SoLuong) FROM GioHang";
            PreparedStatement cauLenh = ketNoi.prepareStatement(sql);
            ResultSet ketQua = cauLenh.executeQuery();
            if (ketQua.next()) {
                double tongTien = ketQua.getDouble(1);
                txtTongTien.setText("" + df.format(tongTien) + " VND");
                txtTongTien_pnlHoaDon.setText(txtTongTien.getText());
                return tongTien;
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanLyHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
        return 0;
    }

    public boolean check() {
        String mauSoLuong = "[0-9]{1,9}";
        if (txtSoLuong.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Số Lượng");
            txtSoLuong.requestFocus();
            return false;
        }
        if (!txtSoLuong.getText().matches(mauSoLuong)) {
            JOptionPane.showMessageDialog(this, "Số Lượng không đúng định dạng");
            txtSoLuong.requestFocus();
            return false;
        }
        int soLuong = Integer.parseInt(txtSoLuong.getText());
        if (soLuong < 1) {
            JOptionPane.showMessageDialog(this, "Số Lượng phải lớn hơn 0");
            txtSoLuong.requestFocus();
            return false;
        }
        return true;
    }
    private void btnThem_GioHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem_GioHangActionPerformed
        try {
            if (check()) {
                if (tblChiTietHoaDon.getRowCount() >= 0) {
                    for (int i = 0; i < tblChiTietHoaDon.getRowCount(); i++) {
                        if (cboMaSanPham.getSelectedItem().toString().equalsIgnoreCase(tblChiTietHoaDon.getValueAt(i, 0).toString())) {
                            JOptionPane.showMessageDialog(this, "Trùng Mã Sản Phẩm");
                            return;
                        }
                    }
                    KetNoiCSDL();
                    DecimalFormat df = new DecimalFormat("###,###");
                    String sql = "INSERT INTO GioHang(MaSanPham,TenSanPham,SoLuong,DonGia,GiamGia) VALUES(?,?,?,?,?)";
                    PreparedStatement cauLenh = ketNoi.prepareStatement(sql);
                    cauLenh.setString(1, cboMaSanPham.getSelectedItem().toString());
                    cauLenh.setString(2, cboTenSanPham.getSelectedItem().toString());
                    cauLenh.setInt(3, Integer.parseInt(txtSoLuong.getText()));
                    cauLenh.setDouble(4, Double.parseDouble(txtDonGia.getText().replace(",", "")));
                    cauLenh.setDouble(5, 0);
                    cauLenh.executeUpdate();
                    ketNoi.close();
                    DoDuLieuLenBangGioHang();
                    TongTien();
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanLyHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnThem_GioHangActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        try {
            if (tblChiTietHoaDon.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(this, "Bạn Chưa Chọn Dòng để xoá");
            } else {
                KetNoiCSDL();
                int viTri = tblChiTietHoaDon.getSelectedRow();
                String sql = "DELETE GioHang WHERE MaSanPham = ?";
                PreparedStatement cauLenh = ketNoi.prepareStatement(sql);
                cauLenh.setString(1, tblChiTietHoaDon.getValueAt(viTri, 0).toString());
                // Ban chac chan muon xoa khong
                int kq = JOptionPane.showConfirmDialog(this, "Bạn Chắc Chắn Xoá");
                if (kq == JOptionPane.YES_OPTION) {
                    cauLenh.executeUpdate();
                    ketNoi.close();
                    DoDuLieuLenBangGioHang();
                    TongTien();
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PhanMem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PhanMem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongTienActionPerformed
        try {
            KetNoiCSDL();
            DecimalFormat df = new DecimalFormat("###,###");
            String sql = "SELECT SUM(DonGia*SoLuong) FROM GioHang";
            PreparedStatement cauLenh = ketNoi.prepareStatement(sql);
            ResultSet ketQua = cauLenh.executeQuery();
            if (ketQua.next()) {
                double tongTien = ketQua.getDouble(1);
                txtTongTien.setText("" + df.format(tongTien) + " VND");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanLyHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtTongTienActionPerformed

    private void txtTienKhachDuaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienKhachDuaKeyReleased
        try {
            if (txtTienKhachDua.getText().isEmpty()) {
                DecimalFormat df = new DecimalFormat("###,###");
                txtTienThua.setText(df.format(-TongTien()) + " VND");
            } else {
                DecimalFormat df = new DecimalFormat("###,###");
                double tienThua = Double.parseDouble(txtTienKhachDua.getText()) - TongTien();
                txtTienThua.setText(df.format(tienThua) + " VND");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtTienKhachDuaKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbrMenu_btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrMenu_btnNewActionPerformed
        try {
            KetNoiCSDL();

            String sql = "DELETE GioHang ";
            PreparedStatement cauLenh = ketNoi.prepareStatement(sql);

            // Ban chac chan muon xoa khong
            int kq = JOptionPane.showConfirmDialog(this, "Bạn Chắc Chắn Làm Mới Tất Cả");
            if (kq == JOptionPane.YES_OPTION) {
                cauLenh.executeUpdate();
                ketNoi.close();
                DoDuLieuLenBangGioHang();
                TongTien();
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PhanMem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PhanMem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbrMenu_btnNewActionPerformed

    private void txtTenKhachHangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenKhachHangKeyReleased
        txtTenKhachHang_pnlHoaDon.setText(txtTenKhachHang.getText());
    }//GEN-LAST:event_txtTenKhachHangKeyReleased
    public void maHoaDon() {
        try {

            KetNoiCSDL();
            DecimalFormat df = new DecimalFormat("###,###");
            String sql = "SELECT TOP 1 D.MaDonHang FROM DonHang D ORDER BY D.MaDonHang DESC";
            PreparedStatement cauLenh = ketNoi.prepareStatement(sql);
            ResultSet ketQua = cauLenh.executeQuery();
            if (ketQua.next()) {
                txtMaHoaDon.setText(ketQua.getInt(1) + "");
            }
            ketNoi.close();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanLyHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public boolean checkKhachhang() {
        String mauSoDienThoai = "0[0-9]{8,11}";
        if (txtTenKhachHang.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Tên Khách Hàng");
            txtTenKhachHang.requestFocus();
            return false;
        }
        if (txtSoDienThoaiKhachHang.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Số Điện Thoại");
            txtSoDienThoaiKhachHang.requestFocus();
            return false;
        }
        if (!txtSoDienThoaiKhachHang.getText().matches(mauSoDienThoai)) {
            JOptionPane.showMessageDialog(this, "Số Điện Thoại không đúng");
            txtSoDienThoaiKhachHang.requestFocus();
            return false;
        }
        if (buttonGroup1.getSelection() == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn giới tính");
            return false;
        }
        if (txtTienKhachDua.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa Nhập Tiền Khách Đưa");
            return false;
        }
        double tienKhachDua = Double.parseDouble(txtTienKhachDua.getText());
        if (tienKhachDua < TongTien()) {
            JOptionPane.showMessageDialog(this, "Chưa đủ tiền thanh toán");
            return false;
        }
        return true;
    }

    public void HoaDon() {
        ArrayList<ListHoaDon> lhd = new ArrayList<>();
        int rowCount = modelGioHang.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            ListHoaDon hd = new ListHoaDon();

        }
    }

    public String maNhanVien() throws ClassNotFoundException, SQLException {
        KetNoiCSDL();
        String sql = "SELECT MaNhanVien FROM NhanVien WHERE HoTen LIKE ?";
        PreparedStatement cauLenh = ketNoi.prepareStatement(sql);
        cauLenh.setString(1, "N'%" + docFile() + "%'");
        ResultSet ketQua = cauLenh.executeQuery();
        if (ketQua.next() == true) {
            String maNV = ketQua.getString(1);
            return ketQua.getString(1);
        }
        return "NV001";
    }
    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        try {
            if (checkKhachhang()) {
                KetNoiCSDL();
                DecimalFormat df = new DecimalFormat("###,###");
                String sql = "EXEC ThanhToanDonHang @HoTenKhachHang = ?,@DienThoai = ?,@GioiTinh = ?,@PhuongThucThanhToan = ?,@MaNhanVien = ?, @SanPhamChiTiet = ?";
                PreparedStatement cauLenh = ketNoi.prepareStatement(sql);
                cauLenh.setString(1, txtTenKhachHang.getText());
                cauLenh.setString(2, txtSoDienThoaiKhachHang.getText());
                if (rdoNam.isSelected()) {
                    cauLenh.setString(3, "Nam");
                } else if (rdoNu.isSelected()) {
                    cauLenh.setString(3, "Nữ");
                }
                cauLenh.setString(4, cboPTThanhToan.getSelectedItem().toString());

                cauLenh.setString(5, maNhanVien());

                ArrayList<ChiTietHoaDon> cthd = new ArrayList<>();
                int rowCount = modelGioHang.getRowCount();

                for (int i = 0; i < rowCount; i++) {
                    ChiTietHoaDon chiTiet = new ChiTietHoaDon();
                    chiTiet.setMaSanPham(modelGioHang.getValueAt(i, 0).toString());
                    chiTiet.setSoLuong(Integer.parseInt(modelGioHang.getValueAt(i, 2).toString()));
                    chiTiet.setDonGia(Double.parseDouble(modelGioHang.getValueAt(i, 3).toString().replace(",", "")));
                    chiTiet.setKhuyenMai(Double.parseDouble(modelGioHang.getValueAt(i, 4).toString().replace(",", "")));

                    cthd.add(chiTiet);
                }

                String sanPhamChiTiet = "[";
                for (int i = 0; i < cthd.size(); i++) {
                    ChiTietHoaDon item = cthd.get(i);
                    sanPhamChiTiet += String.format(
                            "{\"MaSanPham\": \"%s\", \"SoLuong\": %d, \"DonGia\": %.2f, \"KhuyenMai\": %.2f}",
                            item.getMaSanPham(), item.getSoLuong(), item.getDonGia(), item.getKhuyenMai()
                    );
                    if (i < cthd.size() - 1) {
                        sanPhamChiTiet += ",";
                    }
                }
                sanPhamChiTiet += "]";

                cauLenh.setString(6, sanPhamChiTiet);
                cauLenh.executeUpdate();
                ketNoi.close();
                JOptionPane.showMessageDialog(this, "Thanh Toán Thành Công");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanLyHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void btnTaoHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoHoaDonActionPerformed
        String[] thongBao = {"Đồng Ý", "Huỷ"};
        int kq = JOptionPane.showOptionDialog(this, "In Hoá Đơn", "Hoá Đơn", 0, JOptionPane.QUESTION_MESSAGE, null, thongBao, thongBao[0]);
        if (kq == 0) {
            JOptionPane.showMessageDialog(this, "Đã in thành công");
        }
    }//GEN-LAST:event_btnTaoHoaDonActionPerformed

    private void mnuSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSystemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuSystemActionPerformed

    private void mnuSystem_AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSystem_AboutActionPerformed
        JOptionPane.showMessageDialog(this, "PHẦN MỀM QUẢN LÝ GIÀY THỂ THAO\nTác giả: Nguyễn Mộc Toàn\nPhiên Bản: 1.0.0\nNgày tạo: 05/08/2024\nNgày cập nhật: 05/08/2024", "Thông Tin Phần Mềm", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_mnuSystem_AboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new QuanLyHoaDon().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(QuanLyHoaDon.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLyHoaDon.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MnuFile;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnTaoHoaDon;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThem_GioHang;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboKichThuoc;
    private javax.swing.JComboBox<String> cboMaSanPham;
    private javax.swing.JComboBox<String> cboMauSac;
    private javax.swing.JComboBox<String> cboPTThanhToan;
    private javax.swing.JComboBox<String> cboTenSanPham;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblSoLuongKho;
    private javax.swing.JMenu mnuEdit;
    private javax.swing.JMenuItem mnuEdit_DoiMatKhau;
    private javax.swing.JMenuItem mnuFile_Exit;
    private javax.swing.JMenuItem mnuFile_New;
    private javax.swing.JMenuItem mnuFile_Open;
    private javax.swing.JMenuItem mnuFile_Print;
    private javax.swing.JMenuItem mnuFile_Save;
    private javax.swing.JMenu mnuSystem;
    private javax.swing.JMenuItem mnuSystem_About;
    private javax.swing.JPanel pnlGioHang;
    private javax.swing.JPanel pnlHoaDon;
    private javax.swing.JPanel pnlSanPham;
    private javax.swing.JPanel pnlTaoHoaDon;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable tblChiTietHoaDon;
    private javax.swing.JButton tbrMenu_btnExit;
    private javax.swing.JButton tbrMenu_btnNew;
    private javax.swing.JButton tbrMenu_btnPrint;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtSoDienThoaiKhachHang;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenKhachHang;
    private javax.swing.JTextField txtTenKhachHang_pnlHoaDon;
    private javax.swing.JTextField txtTenNhanVien;
    private javax.swing.JTextField txtTienKhachDua;
    private javax.swing.JTextField txtTienThua;
    private javax.swing.JTextField txtTimKiem_MaSanPham;
    private javax.swing.JTextField txtTimKiem_TenSanPham;
    private javax.swing.JTextField txtTongTien;
    private javax.swing.JTextField txtTongTien_pnlHoaDon;
    // End of variables declaration//GEN-END:variables

}
